// <auto-generated />
// MudThemes — "The Matrix" v1.0.0
// Source: Original theme inspired by the Wachowskis' The Matrix (Warner Bros., 1999) — the green digital-rain/code aesthetic and the cold, desaturated real-world colour grade. Not derived from any single official asset. Unofficial fan tribute; not affiliated with or endorsed by Warner Bros.
// Usage:  <MudThemeProvider Theme="@TheMatrixTheme.Theme" @bind-IsDarkMode="_dark" />
// Note:   *Darken/*Lighten palette slots are intentionally left unset — MudBlazor
//         computes them from the base colour. Setting them here would change behaviour.
#nullable enable
using MudBlazor;

namespace MudThemes.Generated;

/// <summary>The Matrix theme for MudBlazor 9.</summary>
public static class TheMatrixTheme
{
    /// <summary>Shared instance. Do not mutate — call <see cref="Create"/> if you need your own.</summary>
    public static MudTheme Theme { get; } = Create();

    /// <summary>A fresh, independently mutable instance.</summary>
    public static MudTheme Create() => new()
    {
        PaletteLight = new PaletteLight
        {
            Black = "#272C34",
            White = "#FFFFFF",
            Primary = "#0B6E2C",
            PrimaryContrastText = "#FFFFFF",
            Secondary = "#0A4D0F",
            SecondaryContrastText = "#FFFFFF",
            Tertiary = "#0E7C86",
            TertiaryContrastText = "#FFFFFF",
            Info = "#1653C7",
            InfoContrastText = "#FFFFFF",
            Success = "#4C7A00",
            SuccessContrastText = "#FFFFFF",
            Warning = "#B35900",
            WarningContrastText = "#FFFFFF",
            Error = "#B3170A",
            ErrorContrastText = "#FFFFFF",
            Dark = "#C7CFD3",
            DarkContrastText = "#000000",
            TextPrimary = "#12181A",
            TextSecondary = "#3E4A4F",
            TextDisabled = "#7C8A8F",
            ActionDefault = "#3E4A4F",
            ActionDisabled = "#7C8A8F",
            ActionDisabledBackground = "#C5CBCE",
            Background = "#DDE3E6",
            BackgroundGray = "#C7CFD3",
            Surface = "#EEF1F3",
            DrawerBackground = "#CBD3D7",
            DrawerText = "#12181A",
            DrawerIcon = "#3E4A4F",
            AppbarBackground = "#CBD3D7",
            AppbarText = "#12181A",
            LinesDefault = "#B7C0C4",
            LinesInputs = "#9FACB1",
            TableLines = "#B7C0C4",
            TableStriped = "#D5DBDE",
            TableHover = "#CDD3D6",
            Divider = "#B7C0C4",
            DividerLight = "#C6CED2",
            Skeleton = "#C7CDD0",
            BorderOpacity = 1,
            HoverOpacity = 0.06,
            RippleOpacity = 0.1,
            RippleOpacitySecondary = 0.2,
            GrayDefault = "#787E80",
            GrayLight = "#969C9F",
            GrayLighter = "#B4BABD",
            GrayDark = "#595F61",
            GrayDarker = "#3B4143",
            OverlayDark = "rgba(33,33,33,0.4980392156862745)",
            OverlayLight = "rgba(255,255,255,0.4980392156862745)",
        },
        PaletteDark = new PaletteDark
        {
            Black = "#27272F",
            White = "#FFFFFF",
            Primary = "#00FF41",
            PrimaryContrastText = "#000000",
            Secondary = "#008F11",
            SecondaryContrastText = "#000000",
            Tertiary = "#4DFFF3",
            TertiaryContrastText = "#000000",
            Info = "#2979FF",
            InfoContrastText = "#000000",
            Success = "#9EFF00",
            SuccessContrastText = "#000000",
            Warning = "#FF8C00",
            WarningContrastText = "#000000",
            Error = "#E10600",
            ErrorContrastText = "#FFFFFF",
            Dark = "#000000",
            DarkContrastText = "#FFFFFF",
            TextPrimary = "#33FF66",
            TextSecondary = "#1EA83D",
            TextDisabled = "#0F5C1E",
            ActionDefault = "#1EA83D",
            ActionDisabled = "#0F5C1E",
            ActionDisabledBackground = "#061F0C",
            Background = "#000000",
            BackgroundGray = "#000000",
            Surface = "#0A0F0A",
            DrawerBackground = "#050805",
            DrawerText = "#33FF66",
            DrawerIcon = "#1EA83D",
            AppbarBackground = "#050805",
            AppbarText = "#33FF66",
            LinesDefault = "#123318",
            LinesInputs = "#1C4D24",
            TableLines = "#123318",
            TableStriped = "#020A04",
            TableHover = "#041408",
            Divider = "#123318",
            DividerLight = "#0B1F0E",
            Skeleton = "#061C0B",
            BorderOpacity = 1,
            HoverOpacity = 0.06,
            RippleOpacity = 0.1,
            RippleOpacitySecondary = 0.2,
            GrayDefault = "#1A8033",
            GrayLight = "#125924",
            GrayLighter = "#0A3314",
            GrayDark = "#21A642",
            GrayDarker = "#29CC52",
            OverlayDark = "rgba(33,33,33,0.4980392156862745)",
            OverlayLight = "rgba(255,255,255,0.4980392156862745)",
        },
        Typography = new Typography
        {
            Default = new DefaultTypography
            {
                FontFamily = ["Share Tech Mono", "Consolas", "monospace"],
                FontWeight = "400",
                FontSize = "0.875rem",
                LineHeight = "1.45",
                LetterSpacing = ".01071em",
                TextTransform = "none",
            },
            H1 = new H1Typography
            {
                FontFamily = ["Share Tech Mono", "Consolas", "monospace"],
                FontSize = "2rem",
                LineHeight = "1.167",
                LetterSpacing = "0.12em",
                TextTransform = "uppercase",
            },
            H2 = new H2Typography
            {
                FontFamily = ["Share Tech Mono", "Consolas", "monospace"],
                FontSize = "1.6rem",
                LineHeight = "1.2",
                LetterSpacing = "0.12em",
                TextTransform = "uppercase",
            },
            H3 = new H3Typography
            {
                FontFamily = ["Share Tech Mono", "Consolas", "monospace"],
                FontSize = "1.35rem",
                LineHeight = "1.167",
                LetterSpacing = "0.12em",
                TextTransform = "uppercase",
            },
            H4 = new H4Typography
            {
                FontFamily = ["Share Tech Mono", "Consolas", "monospace"],
                FontSize = "1.15rem",
                LineHeight = "1.235",
                LetterSpacing = "0.12em",
                TextTransform = "uppercase",
            },
            H5 = new H5Typography
            {
                FontFamily = ["Share Tech Mono", "Consolas", "monospace"],
                FontSize = "1rem",
                LineHeight = "1.334",
                LetterSpacing = "0.12em",
                TextTransform = "uppercase",
            },
            H6 = new H6Typography
            {
                FontFamily = ["Share Tech Mono", "Consolas", "monospace"],
                FontSize = "0.9rem",
                LineHeight = "1.6",
                LetterSpacing = "0.12em",
                TextTransform = "uppercase",
            },
            Subtitle1 = new Subtitle1Typography
            {
                FontFamily = ["Share Tech Mono", "Consolas", "monospace"],
                FontWeight = "400",
                LineHeight = "1.75",
                TextTransform = "none",
            },
            Subtitle2 = new Subtitle2Typography
            {
                FontFamily = ["Share Tech Mono", "Consolas", "monospace"],
                FontWeight = "500",
                LineHeight = "1.57",
                TextTransform = "none",
            },
            Body1 = new Body1Typography
            {
                FontFamily = ["Share Tech Mono", "Consolas", "monospace"],
                FontWeight = "400",
                FontSize = "0.875rem",
                LineHeight = "1.5",
                TextTransform = "none",
            },
            Body2 = new Body2Typography
            {
                FontFamily = ["Share Tech Mono", "Consolas", "monospace"],
                FontWeight = "400",
                FontSize = "0.875rem",
                LineHeight = "1.43",
                TextTransform = "none",
            },
            Button = new ButtonTypography
            {
                FontFamily = ["Share Tech Mono", "Consolas", "monospace"],
                FontWeight = "500",
                FontSize = ".875rem",
                LineHeight = "1.75",
                LetterSpacing = "0.08em",
                TextTransform = "uppercase",
            },
            Caption = new CaptionTypography
            {
                FontFamily = ["Share Tech Mono", "Consolas", "monospace"],
                FontWeight = "400",
                LineHeight = "1.66",
                LetterSpacing = ".03333em",
                TextTransform = "none",
            },
            Overline = new OverlineTypography
            {
                FontFamily = ["Share Tech Mono", "Consolas", "monospace"],
                FontWeight = "400",
                LineHeight = "2.66",
                LetterSpacing = ".08333em",
                TextTransform = "none",
            },
        },
        LayoutProperties = new LayoutProperties
        {
            DefaultBorderRadius = "0px",
            AppbarHeight = "48px",
            DrawerWidthLeft = "220px",
            DrawerWidthRight = "220px",
            DrawerMiniWidthLeft = "56px",
            DrawerMiniWidthRight = "56px",
        },
        Shadows = new Shadow
        {
            Elevation =
            [
                "none",
                "none",
                "none",
                "none",
                "none",
                "none",
                "none",
                "none",
                "none",
                "none",
                "none",
                "none",
                "none",
                "none",
                "none",
                "none",
                "none",
                "none",
                "none",
                "none",
                "none",
                "none",
                "none",
                "none",
                "none",
                "none",
            ],
        },
    };
}
