// <auto-generated />
// MudThemes — "Visual Studio Code" v1.0.0
// Source: microsoft/vscode extensions/theme-defaults/themes: dark_modern.json, dark_plus.json, light_modern.json, light_plus.json. Colors (c) Microsoft Corporation, MIT licensed.
// Usage:  <MudThemeProvider Theme="@VisualStudioCodeTheme.Theme" @bind-IsDarkMode="_dark" />
// Note:   *Darken/*Lighten palette slots are intentionally left unset — MudBlazor
//         computes them from the base colour. Setting them here would change behaviour.
#nullable enable
using MudBlazor;

namespace MudThemes.Generated;

/// <summary>Visual Studio Code theme for MudBlazor 9.</summary>
public static class VisualStudioCodeTheme
{
    /// <summary>Shared instance. Do not mutate — call <see cref="Create"/> if you need your own.</summary>
    public static MudTheme Theme { get; } = Create();

    /// <summary>A fresh, independently mutable instance.</summary>
    public static MudTheme Create() => new()
    {
        PaletteLight = new PaletteLight
        {
            Black = "#272C34",
            White = "#FFFFFF",
            Primary = "#005FB8",
            PrimaryContrastText = "#FFFFFF",
            Secondary = "#AF00DB",
            SecondaryContrastText = "#FFFFFF",
            Tertiary = "#267F99",
            TertiaryContrastText = "#FFFFFF",
            Info = "#001080",
            InfoContrastText = "#FFFFFF",
            Success = "#008000",
            SuccessContrastText = "#FFFFFF",
            Warning = "#795E26",
            WarningContrastText = "#FFFFFF",
            Error = "#A31515",
            ErrorContrastText = "#FFFFFF",
            Dark = "#F8F8F8",
            DarkContrastText = "#000000",
            TextPrimary = "#3B3B3B",
            TextSecondary = "#616161",
            TextDisabled = "#8A8A8A",
            ActionDefault = "#616161",
            ActionDisabled = "#8A8A8A",
            ActionDisabledBackground = "#E7E7E7",
            Background = "#FFFFFF",
            BackgroundGray = "#F8F8F8",
            Surface = "#F8F8F8",
            DrawerBackground = "#F8F8F8",
            DrawerText = "#3B3B3B",
            DrawerIcon = "#616161",
            AppbarBackground = "#F8F8F8",
            AppbarText = "#3B3B3B",
            LinesDefault = "#E5E5E5",
            LinesInputs = "#CECECE",
            TableLines = "#E5E5E5",
            TableStriped = "#F7F7F7",
            TableHover = "#EFEFEF",
            Divider = "#E5E5E5",
            DividerLight = "#EFEFEF",
            Skeleton = "#E9E9E9",
            BorderOpacity = 1,
            HoverOpacity = 0.06,
            RippleOpacity = 0.1,
            RippleOpacitySecondary = 0.2,
            GrayDefault = "#9D9D9D",
            GrayLight = "#BABABA",
            GrayLighter = "#D8D8D8",
            GrayDark = "#808080",
            GrayDarker = "#626262",
            OverlayDark = "rgba(33,33,33,0.4980392156862745)",
            OverlayLight = "rgba(255,255,255,0.4980392156862745)",
        },
        PaletteDark = new PaletteDark
        {
            Black = "#27272F",
            White = "#FFFFFF",
            Primary = "#0078D4",
            PrimaryContrastText = "#FFFFFF",
            Secondary = "#C586C0",
            SecondaryContrastText = "#000000",
            Tertiary = "#4EC9B0",
            TertiaryContrastText = "#000000",
            Info = "#569CD6",
            InfoContrastText = "#000000",
            Success = "#6A9955",
            SuccessContrastText = "#000000",
            Warning = "#DCDCAA",
            WarningContrastText = "#000000",
            Error = "#F85149",
            ErrorContrastText = "#000000",
            Dark = "#181818",
            DarkContrastText = "#FFFFFF",
            TextPrimary = "#CCCCCC",
            TextSecondary = "#9D9D9D",
            TextDisabled = "#6E6E6E",
            ActionDefault = "#9D9D9D",
            ActionDisabled = "#6E6E6E",
            ActionDisabledBackground = "#343434",
            Background = "#1F1F1F",
            BackgroundGray = "#181818",
            Surface = "#202020",
            DrawerBackground = "#181818",
            DrawerText = "#CCCCCC",
            DrawerIcon = "#9D9D9D",
            AppbarBackground = "#181818",
            AppbarText = "#CCCCCC",
            LinesDefault = "#2B2B2B",
            LinesInputs = "#3C3C3C",
            TableLines = "#2B2B2B",
            TableStriped = "#262626",
            TableHover = "#2D2D2D",
            Divider = "#2B2B2B",
            DividerLight = "#262626",
            Skeleton = "#323232",
            BorderOpacity = 1,
            HoverOpacity = 0.06,
            RippleOpacity = 0.1,
            RippleOpacitySecondary = 0.2,
            GrayDefault = "#767676",
            GrayLight = "#5C5C5C",
            GrayLighter = "#424242",
            GrayDark = "#8F8F8F",
            GrayDarker = "#A9A9A9",
            OverlayDark = "rgba(33,33,33,0.4980392156862745)",
            OverlayLight = "rgba(255,255,255,0.4980392156862745)",
        },
        Typography = new Typography
        {
            Default = new DefaultTypography
            {
                FontFamily = ["Cascadia Code", "Cascadia Mono", "Consolas", "Menlo", "DejaVu Sans Mono", "Courier New", "monospace"],
                FontWeight = "400",
                FontSize = "0.8125rem",
                LineHeight = "1.4",
                LetterSpacing = ".01071em",
                TextTransform = "none",
            },
            H1 = new H1Typography
            {
                FontFamily = ["Cascadia Code", "Cascadia Mono", "Consolas", "Menlo", "DejaVu Sans Mono", "Courier New", "monospace"],
                FontSize = "1.625rem",
                LineHeight = "1.167",
            },
            H2 = new H2Typography
            {
                FontFamily = ["Cascadia Code", "Cascadia Mono", "Consolas", "Menlo", "DejaVu Sans Mono", "Courier New", "monospace"],
                FontSize = "1.375rem",
                LineHeight = "1.2",
            },
            H3 = new H3Typography
            {
                FontFamily = ["Cascadia Code", "Cascadia Mono", "Consolas", "Menlo", "DejaVu Sans Mono", "Courier New", "monospace"],
                FontSize = "1.125rem",
                LineHeight = "1.167",
            },
            H4 = new H4Typography
            {
                FontFamily = ["Cascadia Code", "Cascadia Mono", "Consolas", "Menlo", "DejaVu Sans Mono", "Courier New", "monospace"],
                FontSize = "1rem",
                LineHeight = "1.235",
            },
            H5 = new H5Typography
            {
                FontFamily = ["Cascadia Code", "Cascadia Mono", "Consolas", "Menlo", "DejaVu Sans Mono", "Courier New", "monospace"],
                FontSize = "0.9375rem",
                LineHeight = "1.334",
            },
            H6 = new H6Typography
            {
                FontFamily = ["Cascadia Code", "Cascadia Mono", "Consolas", "Menlo", "DejaVu Sans Mono", "Courier New", "monospace"],
                FontSize = "0.8125rem",
                LineHeight = "1.6",
            },
            Subtitle1 = new Subtitle1Typography
            {
                FontFamily = ["Cascadia Code", "Cascadia Mono", "Consolas", "Menlo", "DejaVu Sans Mono", "Courier New", "monospace"],
                FontWeight = "400",
                LineHeight = "1.75",
                TextTransform = "none",
            },
            Subtitle2 = new Subtitle2Typography
            {
                FontFamily = ["Cascadia Code", "Cascadia Mono", "Consolas", "Menlo", "DejaVu Sans Mono", "Courier New", "monospace"],
                FontWeight = "500",
                LineHeight = "1.57",
                TextTransform = "none",
            },
            Body1 = new Body1Typography
            {
                FontFamily = ["Cascadia Code", "Cascadia Mono", "Consolas", "Menlo", "DejaVu Sans Mono", "Courier New", "monospace"],
                FontWeight = "400",
                FontSize = "0.8125rem",
                LineHeight = "1.5",
                TextTransform = "none",
            },
            Body2 = new Body2Typography
            {
                FontFamily = ["Cascadia Code", "Cascadia Mono", "Consolas", "Menlo", "DejaVu Sans Mono", "Courier New", "monospace"],
                FontWeight = "400",
                FontSize = "0.8125rem",
                LineHeight = "1.43",
                TextTransform = "none",
            },
            Button = new ButtonTypography
            {
                FontFamily = ["Cascadia Code", "Cascadia Mono", "Consolas", "Menlo", "DejaVu Sans Mono", "Courier New", "monospace"],
                FontWeight = "500",
                FontSize = ".875rem",
                LineHeight = "1.75",
                TextTransform = "none",
            },
            Caption = new CaptionTypography
            {
                FontFamily = ["Cascadia Code", "Cascadia Mono", "Consolas", "Menlo", "DejaVu Sans Mono", "Courier New", "monospace"],
                FontWeight = "400",
                LineHeight = "1.66",
                LetterSpacing = ".03333em",
                TextTransform = "none",
            },
            Overline = new OverlineTypography
            {
                FontFamily = ["Cascadia Code", "Cascadia Mono", "Consolas", "Menlo", "DejaVu Sans Mono", "Courier New", "monospace"],
                FontWeight = "400",
                LineHeight = "2.66",
                LetterSpacing = ".08333em",
                TextTransform = "none",
            },
        },
        LayoutProperties = new LayoutProperties
        {
            DefaultBorderRadius = "2px",
            AppbarHeight = "40px",
            DrawerWidthLeft = "260px",
            DrawerWidthRight = "260px",
            DrawerMiniWidthLeft = "56px",
            DrawerMiniWidthRight = "56px",
        },
    };
}
